// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTfiSBraFYL2dybbPUhD0cczISPNFDmg',
    appId: '1:586573458067:web:5de9b71b8aa3792acf3b66',
    messagingSenderId: '586573458067',
    projectId: 'urbaneye-002',
    authDomain: 'urbaneye-002.firebaseapp.com',
    storageBucket: 'urbaneye-002.firebasestorage.app',
    measurementId: 'G-BVEMZ2F1DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXi2-0Bqbf3ZvlIjc7at5YtljaAdPbQPA',
    appId: '1:586573458067:android:45aa9bd0bc95f4c6cf3b66',
    messagingSenderId: '586573458067',
    projectId: 'urbaneye-002',
    storageBucket: 'urbaneye-002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlKb_jSnGNj5ySYDin7e-A66B-vC8ShbU',
    appId: '1:586573458067:ios:ab588ea29e4a2765cf3b66',
    messagingSenderId: '586573458067',
    projectId: 'urbaneye-002',
    storageBucket: 'urbaneye-002.firebasestorage.app',
    iosClientId: '586573458067-hgou4caop60n08ub1sv08mfoq77g37t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbaneye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlKb_jSnGNj5ySYDin7e-A66B-vC8ShbU',
    appId: '1:586573458067:ios:ab588ea29e4a2765cf3b66',
    messagingSenderId: '586573458067',
    projectId: 'urbaneye-002',
    storageBucket: 'urbaneye-002.firebasestorage.app',
    iosClientId: '586573458067-hgou4caop60n08ub1sv08mfoq77g37t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbaneye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTfiSBraFYL2dybbPUhD0cczISPNFDmg',
    appId: '1:586573458067:web:955a614379d01297cf3b66',
    messagingSenderId: '586573458067',
    projectId: 'urbaneye-002',
    authDomain: 'urbaneye-002.firebaseapp.com',
    storageBucket: 'urbaneye-002.firebasestorage.app',
    measurementId: 'G-QKVZQF5M7Q',
  );

}